substitutions:
  device_name: presostat
  friendly_name: "Presostat"
  board: esp32-s3-devkitc-1
  pressure_adc_pin: GPIO1
  relay_pin: GPIO6
  relay_inverted: "true"
  button_pin: GPIO7
  i2c_sda_pin: GPIO8
  i2c_scl_pin: GPIO9
  led_pin: GPIO48
  led_rgb_order: GRB
  led_chipset: ws2812
  led_fault_red: "1.0"
  led_fault_green: "0.0"
  led_fault_blue: "0.0"
  led_out_red: "1.0"
  led_out_green: "0.0"
  led_out_blue: "0.0"
  led_in_green_min: "0.2"
  led_in_green_max: "1.0"
  led_calibration_red: "0.0"
  led_calibration_green: "0.0"
  led_calibration_blue: "0.8"
  led_invalid_red: "0.6"
  led_invalid_green: "0.0"
  led_invalid_blue: "0.8"
  led_test_red: "1.0"
  led_test_green: "1.0"
  led_test_blue: "1.0"
  led_off_red: "0.0"
  led_off_green: "0.0"
  led_off_blue: "0.2"
  pressure_voltage_min: "0.5"
  pressure_voltage_max: "4.5"
  pressure_bar_min: "0.0"
  pressure_bar_max: "10.0"
  pressure_hold_min: "3.5"
  pressure_hold_max: "6.0"
  pressure_hold_min_sensor: "sensor.presostat_hold_min"
  pressure_hold_max_sensor: "sensor.presostat_hold_max"
  pressure_fault_min: "1.5"
  wifi_ap_password: "presostat-fallback"

# Inclusion d'une configuration externe pour modularité et réutilisation.
packages:
  twinsen68.presostat:
    url: https://github.com/Twinsen68/presostat.git
    file: presostat_config.yaml
    ref: main
